config/routes.rb
LineaDelTempo::Application.routes.draw do
  
  resources :timeline_events

  resources :events

  resources :timelines

  root to: "pages#home"

end

app/models/event.rb
class Event < ActiveRecord::Base
    
    attr_accessible :caption, :credit, :endDate, :headline, :media, :media_filename, :startDate, :text, :thumbnail,
      :timeline_ids

    has_many :timeline_events, dependent: :destroy
    has_many :timelines, :through => :timeline_events

    validates :startDate, :headline, :presence => true

    # ElasticSearch setup
    include Tire::Model::Search
    include Tire::Model::Callbacks
    mapping do
      indexes :id,              :index    => :not_analyzed    
      indexes :media_filename,  :index    => :not_analyzed
      indexes :headline,        :analyzer => 'snowball', :boost => 100
      indexes :text,            :analyzer => 'snowball'
      indexes :startDate,       :index    => :not_analyzed
      indexes :endDate,         :index    => :not_analyzed  
    end

    settings :index => {
      :analysis => {
        :analyzer => {
          :default => {
            :type => 'snowball'
          }
        }
      }
    }

    def self.search(params)
      tire.search(:load => true) do
        query { string params }
        sort  { by :startDate, 'asc' }     
      end
    end
    # END ElasticSearch setup


    # def start_date
    #   short_date(:startDate)
    # end
    # def end_date
    #   short_date(:endDate)
    # end

    # def short_date(method)      
    #   date = send(method)
    #   return nil if date.blank?
    #   parts = date.to_date.to_s.split('-')
    #   data = parts[0]
    #   if parts[1] != '01' or (parts[1] == '01' && parts[2] != '01')
    #     data << "-#{parts[1]}"
    #     if parts[2] != '01'
    #       data << "-#{parts[2]}"
    #     end
    #   end
    #   data
    # end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    if params[:query].present?
       @events = Event.search(params[:query])
    else
       @events = Event.all
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg
  .fields
    = f.label :headline, "Titolo"
    = f.text_field :headline, class: "input-block-level"
  .fields
    = f.label :startDate, "Data inizio"
    = f.text_field :startDate

  .fields
    = f.label :endDate, "Data fine"
    = f.text_field :endDate

  .fields
    = f.label :text, "Testo"
    = f.text_area :text, class: "input-block-level"

  .fields
    = f.label :media
    = f.text_field :media, class: "input-block-level"

  .fields
    = f.label :credit, "Crediti"
    = f.text_field :credit, class: "input-block-level"

  .fields
    = f.label :caption, "Legenda"
    = f.text_field :caption, class: "input-block-level"

  .fields
    = f.label :thumbnail
    = f.text_field :thumbnail, class: "input-block-level"

  .fields
    = f.label :media_filename
    = f.text_field :media_filename, class: "input-block-level"

  %fieldset
    %legend
      Collega l'evento a linea del tempo:  
    .fields
      = hidden_field_tag "event[timeline_ids][]", nil
      - Timeline.all.each do |timeline|
        = check_box_tag "event[timeline_ids][]", timeline.id, @event.timeline_ids.include?(timeline.id), id: dom_id(timeline)
        = label_tag dom_id(timeline), timeline.headline, style: "display:inline"
        %br
    %br
  .form-actions
    = f.submit 'Salva', class: "btn btn-primary"

app/views/events/_search_form.html.haml
= form_tag events_path, :method => :get do
  %p
    = text_field_tag :query, params[:query]
    = submit_tag "Cerca Eventi", :name => nil
    = link_to 'annulla ricerca', events_path if defined?(@events)

app/views/events/edit.html.haml
%h1 Modifica Evento
%br
= render 'form'
%br
= link_to 'Events', events_path
|
= link_to 'Timelines', timelines_path

app/views/events/index.html.haml
%h1 Eventi
%br

= render 'search_form'


%table.table
  %tr
    %th Titolo
    %th Dal
    %th Al
    %th Testo
    %th 
    %th

  - @events.each do |event|
    %tr
      %td= link_to event.headline, event
      %td= event.startDate
      %td= event.endDate
      %td= "#{event.text[0..30]}..."
      
      %td= link_to 'Modifica', edit_event_path(event)
      %td= link_to 'Elimina', event, method: :delete, data: { confirm: 'Sei Sicuro?' }

%br

= link_to 'Nuovo Evento', new_event_path
|
= link_to 'Eventi', events_path
|
= link_to 'Linee del Tempo', timelines_path

app/views/events/new.html.haml
%h1 Nuovo Evento
%br
= render 'form'
%br
= link_to 'Events', events_path
|
= link_to 'Timelines', timelines_path

app/views/events/show.html.haml
%p.alert= notice


%h1
  = @event.headline

%p
  = [@event.startDate, @event.endDate].join(" -> ") 
  
%p
  = @event.text

%p
  = @event.media  

%p
  = @event.credit  

%p
  = @event.caption  

%p
  = @event.thumbnail  

%p
  = @event.media_filename

= youtube_embed("#{@event.media_filename}")

%br

= link_to 'Modifica', edit_event_path(@event)
\|
= link_to 'Eventi', events_path