config/routes.rb
LineaDelTempo::Application.routes.draw do
  
  resources :timeline_events

  resources :events

  resources :timelines

  root to: "pages#home"

end

app/models/timeline_event.rb
class TimelineEvent < ActiveRecord::Base
  belongs_to :timeline
  belongs_to :event
end

app/controllers/timeline_events_controller.rb
class TimelineEventsController < ApplicationController
  # GET /timeline_events
  # GET /timeline_events.json
  def index
    @timeline_events = TimelineEvent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @timeline_events }
    end
  end

  # GET /timeline_events/1
  # GET /timeline_events/1.json
  def show
    @timeline_event = TimelineEvent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @timeline_event }
    end
  end

  # GET /timeline_events/new
  # GET /timeline_events/new.json
  def new
    @timeline_event = TimelineEvent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @timeline_event }
    end
  end

  # GET /timeline_events/1/edit
  def edit
    @timeline_event = TimelineEvent.find(params[:id])
  end

  # POST /timeline_events
  # POST /timeline_events.json
  def create
    @timeline_event = TimelineEvent.new(params[:timeline_event])

    respond_to do |format|
      if @timeline_event.save
        format.html { redirect_to @timeline_event, notice: 'Timeline event was successfully created.' }
        format.json { render json: @timeline_event, status: :created, location: @timeline_event }
      else
        format.html { render action: "new" }
        format.json { render json: @timeline_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /timeline_events/1
  # PUT /timeline_events/1.json
  def update
    @timeline_event = TimelineEvent.find(params[:id])

    respond_to do |format|
      if @timeline_event.update_attributes(params[:timeline_event])
        format.html { redirect_to @timeline_event, notice: 'Timeline event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @timeline_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timeline_events/1
  # DELETE /timeline_events/1.json
  def destroy
    @timeline_event = TimelineEvent.find(params[:id])
    @timeline_event.destroy

    respond_to do |format|
      format.html { redirect_to timeline_events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/timeline_events_helper.rb
module TimelineEventsHelper
end

app/views/timeline_events/_form.html.haml
= form_for @timeline_event do |f|
  - if @timeline_event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@timeline_event.errors.count, "error")} prohibited this timeline_event from being saved:"
      %ul
        - @timeline_event.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/timeline_events/edit.html.haml
%h1 Editing timeline_event

= render 'form'

= link_to 'Show', @timeline_event
\|
= link_to 'Back', timeline_events_path

app/views/timeline_events/index.html.haml
%h1 Listing timeline_events

%table
  %tr
    %th
    %th
    %th

  - @timeline_events.each do |timeline_event|
    %tr
      %td= link_to 'Show', timeline_event
      %td= link_to 'Edit', edit_timeline_event_path(timeline_event)
      %td= link_to 'Destroy', timeline_event, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Timeline event', new_timeline_event_path

app/views/timeline_events/new.html.haml
%h1 New timeline_event

= render 'form'

= link_to 'Back', timeline_events_path

app/views/timeline_events/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_timeline_event_path(@timeline_event)
\|
= link_to 'Back', timeline_events_path