config/routes.rb
LineaDelTempo::Application.routes.draw do
  
  resources :timeline_events

  resources :events

  resources :timelines

  root to: "pages#home"

end

app/models/timeline.rb
class Timeline < ActiveRecord::Base
  attr_accessible :caption, :credit, :headline, :media, :startDate, :text, :event_ids

  has_many :timeline_events, dependent: :destroy
  has_many :events, :through => :timeline_events

  def to_label
    headline
  end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController

  def index
    @timelines = Timeline.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @timelines }
    end
  end

  def show
    @timeline = Timeline.find(params[:id])

    @timeline = Timeline.find(params[:id])
    @events   = @timeline.events.where('media IS NOT NULL OR text IS NOT NULL')
    @events_all = @timeline.events.order(:startDate)
    respond_to do |format|
      format.html
      format.json do
        # FIXME: this is terribly ugly but work so far
        dates = @events.map do |event| 
          return_event = event.attributes
          return_event[:asset] = {:media => event.media, :credit => event.credit, :caption => event.caption}
          # return_event['startDate'] = return_event['startDate'].to_s.gsub('-',',')
          # return_event['endDate'] = return_event['endDate'].to_s.gsub('-',',')
          return_event
        end
        timeline = @timeline.attributes
        # timeline[:asset] ={:media => @timeline.media, :credit => @timeline.credit, :caption => @timeline.caption}
        timeline[:type] = 'default'
        timeline[:date] = dates
        hash = {:timeline => timeline}
        render :json => hash.to_json
      end
    end
  end

  def new
    @timeline = Timeline.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @timeline }
    end
  end

  def edit
    @timeline = Timeline.find(params[:id])
  end

  def create
    @timeline = Timeline.new(params[:timeline])

    respond_to do |format|
      if @timeline.save
        format.html { redirect_to @timeline, notice: 'Timeline was successfully created.' }
        format.json { render json: @timeline, status: :created, location: @timeline }
      else
        format.html { render action: "new" }
        format.json { render json: @timeline.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @timeline = Timeline.find(params[:id])

    respond_to do |format|
      if @timeline.update_attributes(params[:timeline])
        format.html { redirect_to @timeline, notice: 'Timeline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @timeline.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @timeline = Timeline.find(params[:id])
    @timeline.destroy

    respond_to do |format|
      format.html { redirect_to timelines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/views/timelines/_form.html.haml
= form_for @timeline do |f|
  - if @timeline.errors.any?
    #error_explanation
      %h2= "#{pluralize(@timeline.errors.count, "error")} prohibited this timeline from being saved:"
      %ul
        - @timeline.errors.full_messages.each do |msg|
          %li= msg
  .fields
    = f.label :headline
    = f.text_field :headline, html: {class: "input-large"}

  .fields
    = f.label :startDate
    = f.text_field :startDate

  .fields
    = f.label :text
    = f.text_area :text

  .fields
    = f.label :media
    = f.text_field :media

  .fields
    = f.label :credit
    = f.text_field :credit

  .fields
    = f.label :caption
    = f.text_field :caption

  .actions
    = f.submit 'Salva', class: "btn btn-primary"

app/views/timelines/edit.html.haml
%h1 Modifica Linea del Tempo
%br
= render 'form'
%br
= link_to 'Linee del Tempo', timelines_path
|
= link_to 'Eventi', events_path

app/views/timelines/index.html.haml
%h1 Linee del Tempo

%ul.thumbnails
  - @timelines.each do |timeline|
    %li.span3
      = link_to(timeline, :class => :thumbnail) do
        - if timeline.media.blank?
          - if !timeline.events.where('media IS NOT NULL').order("events.startDate").limit(1).first.blank?
            = image_tag timeline.events.where('media IS NOT NULL').order("events.startDate").limit(1).first.media 
        - else
          = image_tag timeline.media
        %h5= timeline.headline
        %p= timeline.caption


%br
%table.table
  %tr
    %th Titolo
    %th Dal
    %th Testo
    %th 
    %th 

  - @timelines.each do |timeline|
    %tr
      %td= link_to timeline.headline, timeline
      %td= timeline.startDate
      %td= "#{timeline.text[0..30]}..."
      %td= link_to 'Modifica', edit_timeline_path(timeline)
      %td= link_to 'Elimina', timeline, method: :delete, data: { confirm: 'Are you sure?' }

%br


= link_to 'Nuova Linea del Tempo', new_timeline_path
|
= link_to 'Linee del Tempo', timelines_path
|
= link_to 'Eventi', events_path

app/views/timelines/new.html.haml
%h1 Nuova Linea del Tempo
%br
= render 'form'
%br
= link_to 'Linee del Tempo', timelines_path
|
= link_to 'Eventi', events_path

app/views/timelines/show.html.haml
%p.alert= notice

%h1
  = @timeline.headline

%p
  = @timeline.startDate

%p
  = @timeline.text

%p
  = @timeline.media  

%p
  = @timeline.credit

%p
  = @timeline.caption  


= link_to 'Modifica', edit_timeline_path(@timeline)
|
= link_to 'Linee del Tempo', timelines_path
|
= link_to 'Eventi', events_path